"""Beacon chain genesis state generation.

Uses pre-generated fixtures from builder-playground with Electra fork enabled.
"""

from __future__ import annotations

import shutil
from pathlib import Path

# Path to fixtures directory
FIXTURES_DIR = Path(__file__).parent / "fixtures"


def generate_beacon_genesis(output_dir: Path) -> None:
    """Copy beacon chain genesis fixtures.

    The fixtures were generated by builder-playground with Electra fork
    enabled and 100 validators using Prysm interop keys.

    Args:
        output_dir: Directory to write genesis files
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Copy fixtures as-is
    shutil.copy(FIXTURES_DIR / "genesis.ssz", output_dir / "genesis.ssz")
    shutil.copy(FIXTURES_DIR / "config.yaml", output_dir / "config.yaml")

    # Write deploy_block.txt
    (output_dir / "deploy_block.txt").write_text("0")
    (output_dir / "deposit_contract_block.txt").write_text("0")

    print("  Beacon genesis copied from fixtures")
