"""Execution layer genesis generation.

Uses pre-generated fixture from builder-playground.
"""

from __future__ import annotations

import shutil
from pathlib import Path

# Path to fixtures directory
FIXTURES_DIR = Path(__file__).parent / "fixtures"


def generate_el_genesis(output_path: Path, _timestamp: int = 0) -> None:
    """Copy the execution layer genesis file from fixture.

    The fixture was generated by builder-playground and includes proper
    deposit contract and pre-funded accounts.

    Args:
        output_path: Path to write the genesis.json file
        _timestamp: Unused (kept for API compatibility)
    """
    fixture_path = FIXTURES_DIR / "el_genesis.json"

    # Ensure parent directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Copy fixture as-is
    shutil.copy(fixture_path, output_path)
